### PR TITLE
Add some missing manifestos

### PR DESCRIPTION
**Pull request by derylspielman**
Programming, Motherfucker is a true raw manifesto from Zed Shaw
that poopoos on the fact that Agile has become bloated and spoiled.

DataOps is a newer manifesto around data anlytics.

### CODE REVIEW

**Comment by derylspielman** [comment]
@meantheory are you actively maintaining this?

**Comment by khalilswdp** [comment]
There's also the Reactive Manifesto, The 12-factor app manifesto. I can make a new project with all really awesome manifestos one can find... for ease of search

**Comment by meantheory** [comment]
Active is a strong word 😆  but I do maintain it.

**Comment by meantheory** [comment]
Happy to defer to another resource that is more actively maintained if one exists.

**Pull request merged**
